name: continuous deployment
on:
    push:
        branches:
            - main
        paths:
            - 'src/terraform/**'
            - '.github/workflow/**'
    workflow_dispatch:

permissions:
    contents: 'read'
    id-token: 'write'


env:
    TERRAFORM_WORKING_DIRECTORY: 'src/terraform'
    PYTHON_VERSION: '3.9'
    ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    ARM_TENANT_ID: ${{ secrets.TENANT_ID}}
    ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID}}
    AZURE_FUNCTIONAPP_PACKAGE_PATH: . 
    PYTHON_WORKING_DIRECTORY: 'src/python_function'
    RESOURCE_GROUP_NAME: rg-resumecloudchallenge-dev
    FUNCITONAPP_NAME: fa-resumecloudchallenge


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
    
          - name: Setup Python version
            uses: actions/setup-python@v5
            with:
              python-version: ${{ env.PYTHON_VERSION }}
    
          - name: Install dependencies
            working-directory: ${{ env.PYTHON_WORKING_DIRECTORY }}
            run: |
              python -m pip install --upgrade pip
              pip install --target="./.python_packages/lib/site-packages" -r requirements.txt
              ls -a
    
          # Optional: Add step to run tests here
    
          - name: Zip artifact for deployment
            working-directory: ${{ env.PYTHON_WORKING_DIRECTORY }}
            run: zip release.zip ./* -r
    
          - name: Upload artifact for deployment job
            uses: actions/upload-artifact@v4
            with:
              name: python-app
              path: |
                src/python_function/release.zip
            
    terraform:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            -   name: Setup Terraform
                uses: hashicorp/setup-terraform@v3
                with: 
                    terraform_version: 1.5.5
                    terraform_wrapper: false
            
            -   name: Terraform init
                working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
                run: terraform init

            -   name: Terraform apply
                working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
                run: |
                    terraform apply --auto-approve
        
    deploy:
        runs-on: ubuntu-latest
        needs: [ "build", "terraform"]
        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                name: python-app
      
            - name: Azure CLI login
              uses: azure/login@v1
              with:
                azcliversion: 2.30.1
                client-id: ${{env.ARM_CLIENT_ID}}
                tenant-id: ${{env.ARM_TENANT_ID}}
                subscription-id: ${{env.ARM_SUBSCRIPTION_ID}}

            - name: 'Deploy to Azure Functions'
              run: |
                az functionapp deployment source config-zip \
                  --resource-group ${{env.RESOURCE_GROUP_NAME}} \
                  --name ${{env.FUNCITONAPP_NAME}} \
                  --src "./release.zip" --build-remote true