# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: continuous integration

on:
  push:
    branches:
      - main
    paths:
      - 'src/python_function/**'
  workflow_dispatch:

permissions:
    contents: 'read'
    id-token: 'write'

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: . 
  PYTHON_VERSION: '3.9' 
  WORKING_DIRECTORY: 'src/python_function'
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID}}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID}}
  RESOURCE_GROUP_NAME: rg-resumecloudchallenge-dev
  FUNCITONAPP_NAME: fa-resumecloudchallenge

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          python -m pip install --upgrade pip
          pip install --target="./.python_packages/lib/site-packages" -r requirements.txt
          ls -a

      # Optional: Add step to run tests here