name: CI
on:
    push:
        branches:
            - main
        paths:
            - 'src/python_function/**'
    workflow_dispatch:

env:
    WORKING_DIRECTORY: './src/python_function'
    PYTHON_VERSION: '3.9'

jobs:  
    run-function:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: set python version
              uses: actions/setup-python@v1
              with:
                python-version: ${{ env.PYTHON_VERSION }}
            
            - name: Setup venv and Install dependencies
              working-directory: ${{ env.WORKING_DIRECTORY }}
              run: |
                python -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
            
            # Add tests

            # list terraform states
            -   name: Terraform
                working-directory: src/terraform
                run: |
                    ls
                    terraform init
                    terraform state list
    