name: CI
on:
    push:
        branches:
            - main
        paths:
            - 'src/python_function/**'
    workflow_dispatch:

permissions:
    contents: 'read'
    id-token: 'write'

env:
    WORKING_DIRECTORY: './src/python_function'
    PYTHON_VERSION: '3.9'
    ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    ARM_TENANT_ID: ${{ secrets.TENANT_ID}}
    ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID}}
    AZURE_FUNCTIONAPP_NAME: "fa-resumecloudchallenge"
    AZURE_FUNCTIONAPP_PACKAGE_PATH: "src/python_function"

jobs:  
    run-function:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
              uses: actions/setup-python@v4
              with:
                python-version: ${{ env.PYTHON_VERSION }}
            
            - name: Setup venv and Install dependencies
              working-directory: ${{ env.WORKING_DIRECTORY }}
              run: |
                python -m pip install --upgrade pip
                pip install --target="./.python_packages/lib/site-packages" -r requirements.txt
            
            - name: Zip python_function
              run: |
                cd "src/python_function"
                zip -r ../python_function.zip ./*
            
            
            - name: 'Run Azure Functions Action'
              uses: Azure/functions-action@v1
              id: fa
              with:
                  app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
                  package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
                  publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
                  scm-do-build-during-deployment: true
                  enable-oryx-build: true
            
