name: Provision Terraform
on:
    push:
        branches:
            - main
        paths:
            - 'src/terraform/**'
            - '.github/workflow/**'
    workflow_dispatch:

env:
    TERRAFORM_WORKING_DIRECTORY: 'src/terraform'
    PYTHON_VERSION: '3.9'
    ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    ARM_TENANT_ID: ${{ secrets.TENANT_ID}}
    ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID}}

jobs:  
    terraform:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            -   name: Setup Terraform
                uses: hashicorp/setup-terraform@3
                with: 
                    terraform_version: 1.5.5
                    terraform_wrapper: false
            
            -   name: Terraform init
                working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
                run: terraform init

            -   name: Terraform apply
                working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
                run: |
                    terraform apply --auto-approve